client
dev tun
proto udp

remote 192.168.122.96 1194

resolv-retry infinite
nobind

persist-key
persist-tun

ca /etc/openvpn/client/ca.crt
cert /etc/openvpn/client/client.crt
key /etc/openvpn/client/client.key

remote-cert-tls server

cipher AES-256-GCM
auth SHA256

verb 3
