Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "dev" do |dev|
    dev.vm.hostname = "dev"
    dev.vm.network "private_network",
      ip: "192.168.56.10",
      libvirt__network_name: "lesson12",
      libvirt__host_ip: "192.168.56.1",
      libvirt__dhcp_enabled: false,
      libvirt__forward_mode: "nat",
      libvirt__netmask: "255.255.255.0"
  end

  config.vm.define "prod" do |prod|
    prod.vm.hostname = "prod"
    prod.vm.network "private_network",
      ip: "192.168.56.11",
      libvirt__network_name: "lesson12",
      libvirt__host_ip: "192.168.56.1",
      libvirt__dhcp_enabled: false,
      libvirt__forward_mode: "nat",
      libvirt__netmask: "255.255.255.0"
  end
end
