apiVersion: v1
kind: Secret
metadata:
  name: wordpress-db
  namespace: dev
type: Opaque
stringData:
  mysql-root-password: root1234
  mysql-user: wordpress
  mysql-password: wordpress1234
  mysql-database: wordpress
