FROM debian:11

RUN printf '%s\n' \
    'deb http://archive.debian.org/debian bullseye main' \
    'deb http://archive.debian.org/debian bullseye-updates main' \
    > /etc/apt/sources.list && \
    apt-get -o Acquire::Check-Valid-Until=false update && \
    apt-get install -y nginx && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /opt/www

COPY index.html /opt/www/index.html
COPY nginx.conf /etc/nginx/sites-available/default

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]
