apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wordpress.mysqlConfigName" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
data:
  MYSQL_DATABASE: {{ .Values.database.name | quote }}
  MYSQL_USER: {{ .Values.database.user | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wordpress.wordpressConfigName" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
data:
  WORDPRESS_DB_HOST: {{ include "wordpress.mysqlServiceName" . | quote }}
  WORDPRESS_DB_NAME: {{ .Values.database.name | quote }}
  WORDPRESS_DB_USER: {{ .Values.database.user | quote }}
