{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "wordpress.fullname" . }}-mysql-ingress
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "wordpress.mysqlSelectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "wordpress.wordpressSelectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.mysql.service.port }}
{{- end }}
