apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.mysqlSecretName" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.secrets.mysqlRootPassword | quote }}
  MYSQL_PASSWORD: {{ .Values.secrets.databasePassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.wordpressSecretName" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
type: Opaque
stringData:
  WORDPRESS_DB_PASSWORD: {{ .Values.secrets.databasePassword | quote }}
