Vagrant.configure("2") do |config|
  config.vm.box = "cloud-image/ubuntu-24.04"
  config.vm.box_check_update = false

  key_dir = File.expand_path(".vagrant", __dir__)
  key_path = File.join(key_dir, "server_key")

  Dir.mkdir(key_dir) unless Dir.exist?(key_dir)

  unless File.exist?(key_path)
    system("ssh-keygen", "-q", "-t", "ed25519", "-N", "", "-f", key_path)
  end

  config.vm.define "server" do |server|
    server.vm.hostname = "server"

    server.vm.network "private_network",
      ip: "192.168.56.11"

    server.vm.provider :libvirt do |libvirt|
      libvirt.memory = 1024
      libvirt.cpus = 1
    end

    server.vm.provision "file",
      source: "#{key_path}.pub",
      destination: "/tmp/server_key.pub"

    server.vm.provision "shell",
      path: "provision-server.sh"
  end

  config.vm.define "client" do |client|
    client.vm.hostname = "client"

    client.vm.network "private_network",
      ip: "192.168.56.10"

    client.vm.provider :libvirt do |libvirt|
      libvirt.memory = 1024
      libvirt.cpus = 1
    end

    client.vm.provision "file",
      source: key_path,
      destination: "/home/vagrant/.ssh/server_key"

    client.vm.provision "shell",
      path: "provision-client.sh"
  end
end
